"""updating migration

Revision ID: 1b6c1dd47c96
Revises: 755164631da5
Create Date: 2024-12-16 15:54:17.158993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6c1dd47c96'
down_revision = '755164631da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)

    # ### end Alembic commands ###
