"""Add phone_num to users

Revision ID: 408b5bf6c647
Revises: 19cacb17380d
Create Date: 2024-12-16 15:04:57.633912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408b5bf6c647'
down_revision = '19cacb17380d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('behavior', sa.String(length=255), nullable=True),
    sa.Column('medication_note', sa.String(length=255), nullable=True),
    sa.Column('dietary_note', sa.String(length=255), nullable=True),
    sa.Column('preview_image', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('booking_type', sa.String(length=50), nullable=False),
    sa.Column('drop_off_date', sa.DateTime(), nullable=False),
    sa.Column('pick_up_date', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.drop_table('pet_images')
    op.drop_table('booking')
    op.drop_table('pets')
    # ### end Alembic commands ###
