"""booking service table

Revision ID: 755164631da5
Revises: 408b5bf6c647
Create Date: 2024-12-16 15:11:27.246009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755164631da5'
down_revision = '408b5bf6c647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('booking_type', sa.String(length=50), nullable=False),
    sa.Column('drop_off_date', sa.DateTime(), nullable=False),
    sa.Column('pick_up_date', sa.DateTime(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_service',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('booking_id', 'service_id')
    )
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=False),
    sa.Column('booking_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('drop_off_date', sa.DATETIME(), nullable=False),
    sa.Column('pick_up_date', sa.DATETIME(), nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('booking_service')
    op.drop_table('bookings')
    # ### end Alembic commands ###
